export const earningsHistoryData = [
    {
        id: "ERN-1001",
        orderId: "ORD-1001",
        productId: "PRD-101",
        productName: "Wireless Gaming Mouse",
        customerId: "CUS-201",
        customerName: "John Smith",
        orderAmount: 1200,
        commission: 120,
        earningAmount: 1080,
        quantity: 1,
        paymentMethod: "Card",
        paymentStatus: "paid",
        earningStatus: "available", // available | paid_out | pending
        earnedDate: "2026-06-15T10:25:00Z",
        payoutId: null,
    },
    {
        id: "ERN-1002",
        orderId: "ORD-1002",
        productId: "PRD-102",
        productName: "Mechanical Keyboard",
        customerId: "CUS-202",
        customerName: "Sarah Johnson",
        orderAmount: 2500,
        commission: 250,
        earningAmount: 2250,
        quantity: 1,
        paymentMethod: "bKash",
        paymentStatus: "paid",
        earningStatus: "available",
        earnedDate: "2026-06-15T13:42:00Z",
        payoutId: null,
    },
    {
        id: "ERN-1003",
        orderId: "ORD-1003",
        productId: "PRD-103",
        productName: "USB-C Hub",
        customerId: "CUS-203",
        customerName: "David Brown",
        orderAmount: 850,
        commission: 85,
        earningAmount: 765,
        quantity: 1,
        paymentMethod: "Nagad",
        paymentStatus: "paid",
        earningStatus: "available",
        earnedDate: "2026-06-14T09:15:00Z",
        payoutId: null,
    },
    {
        id: "ERN-1004",
        orderId: "ORD-1004",
        productId: "PRD-104",
        productName: "Bluetooth Speaker",
        customerId: "CUS-204",
        customerName: "Emily Davis",
        orderAmount: 1800,
        commission: 180,
        earningAmount: 1620,
        quantity: 1,
        paymentMethod: "Card",
        paymentStatus: "paid",
        earningStatus: "available",
        earnedDate: "2026-06-14T15:30:00Z",
        payoutId: null,
    },
    {
        id: "ERN-1005",
        orderId: "ORD-1005",
        productId: "PRD-105",
        productName: "Laptop Stand",
        customerId: "CUS-205",
        customerName: "Michael Wilson",
        orderAmount: 950,
        commission: 95,
        earningAmount: 855,
        quantity: 1,
        paymentMethod: "Rocket",
        paymentStatus: "paid",
        earningStatus: "paid_out",
        earnedDate: "2026-06-13T11:10:00Z",
        payoutId: "PAY-3001",
    },
    {
        id: "ERN-1006",
        orderId: "ORD-1006",
        productId: "PRD-106",
        productName: "Gaming Headset",
        customerId: "CUS-206",
        customerName: "Sophia Taylor",
        orderAmount: 3200,
        commission: 320,
        earningAmount: 2880,
        quantity: 1,
        paymentMethod: "Card",
        paymentStatus: "pending",
        earningStatus: "paid_out",
        earnedDate: "2026-06-13T16:20:00Z",
        payoutId: "PAY-3001",
    },
    {
        id: "ERN-1007",
        orderId: "ORD-1007",
        productId: "PRD-107",
        productName: "RGB Mouse Pad",
        customerId: "CUS-207",
        customerName: "James Anderson",
        orderAmount: 700,
        commission: 70,
        earningAmount: 630,
        quantity: 1,
        paymentMethod: "bKash",
        paymentStatus: "refunded",
        earningStatus: "available",
        earnedDate: "2026-06-12T09:45:00Z",
        payoutId: null,
    },
    {
        id: "ERN-1008",
        orderId: "ORD-1008",
        productId: "PRD-108",
        productName: "Webcam HD",
        customerId: "CUS-208",
        customerName: "Olivia Martinez",
        orderAmount: 2200,
        commission: 220,
        earningAmount: 1980,
        quantity: 1,
        paymentMethod: "Card",
        paymentStatus: "paid",
        earningStatus: "available",
        earnedDate: "2026-06-12T14:12:00Z",
        payoutId: null,
    },
    {
        id: "ERN-1009",
        orderId: "ORD-1009",
        productId: "PRD-109",
        productName: "Portable SSD 1TB",
        customerId: "CUS-209",
        customerName: "William Thomas",
        orderAmount: 5500,
        commission: 550,
        earningAmount: 4950,
        quantity: 1,
        paymentMethod: "Card",
        paymentStatus: "paid",
        earningStatus: "pending",
        earnedDate: "2026-06-11T10:18:00Z",
        payoutId: null,
    },
    {
        id: "ERN-1010",
        orderId: "ORD-1010",
        productId: "PRD-110",
        productName: "USB Microphone",
        customerId: "CUS-210",
        customerName: "Benjamin Moore",
        orderAmount: 2800,
        commission: 280,
        earningAmount: 2520,
        quantity: 1,
        paymentMethod: "Nagad",
        paymentStatus: "pending",
        earningStatus: "pending",
        earnedDate: "2026-06-11T17:30:00Z",
        payoutId: null,
    },
];